/**
 * Validation constants for Business Units and Departments
 */

export const ALLOWED_BUSINESS_UNITS = [
  'Organization Functions',
  'Chief Technology Office',
  'Co-Commercialization',
  'Enterprise Commercial',
  'Growth Markets',
  'Enterprise Clinical',
  'Indegene Japan',
  'Enterprise Medical',
  'Medical Devices',
  'Multi-Channel Marketing',
  'Strategy and Development',
  'Enterprise Product Office',
  'Transformative Software Solutions',
  'Finance and Legal',
  'Global Operations',
  'People Practices & Systems',
  'Sales Lifesciences'
];

export const ALLOWED_DEPARTMENTS = [
  'Leadership & Organization Development',
  'Chief Technology Office',
  'Enterprise Informatics',
  'Enterprise Product Office',
  'Enterprise Tech Office',
  'Research & Development',
  'Co-Commercialization',
  'Omnichannel Acceleration',
  'Enterprise Commercial',
  'Omnichannel Solutions',
  'Enterprise Commercial Activation and Change Management',
  'Content Transformation & Solutions',
  'Enterprise Commercial Delivery Services',
  'Customer Experience Success Office (CESO)',
  'Digital Enablement',
  'Data and Analytics',
  'Content and Design Solutions',
  'CXD Content and Experience Design',
  'Web and Portal Solutions',
  'Patient Experience',
  'Customer Advisory and Experience',
  'Digital Innovation and Transformation',
  'Campaign and Channel Operations',
  'ECS Platforms and Technology',
  'ECS Solutioning Presales and Marketing',
  'BU Sales',
  'Campaign Ops',
  'Growth Markets',
  'GM - Sales & Solutions',
  'Enterprise Clinical',
  'Clinical Data Management',
  'RWD & Biostats',
  'Clinical Operations',
  'Digital Patient Recruitment and Engagement',
  'Indegene Japan',
  'Sales - Japan',
  'Enterprise Medical',
  'Enterprise Medical Client Partnership and Advisory',
  'Medical Affairs',
  'Medical Communication',
  'Material Review, Operations and Compliance',
  'Promotional and Medical Review',
  'Learning & Development Solutions',
  'Health Care Practitioners (HCP)',
  'Learning and Development',
  'Safety',
  'Pharmacovigilance',
  'Regulatory Affairs',
  'Labelling Solutions',
  'Packaging Artwork and Labelling',
  'Health Economics & Outcomes Research',
  'PRMA Common',
  'Enterprise Medical Platforms and Technology',
  'Medical Devices',
  'Device Technology',
  'Quality and Regulatory',
  'Solutioning Sales and Marketing',
  'Medical Content Solutions',
  'Multi-Channel Marketing',
  'Medical Engagement Solutions',
  'Digital Solutions',
  'Strategy and Development',
  'Corporate Planning',
  'Corporate Strategy',
  'Corporate Development',
  'Enterprise Product Office',
  'Product - Medical',
  'Engineering - Commercial',
  'Product - Commercial',
  'Engineering - Medical',
  'Transformative Software Solutions',
  'Engineering Office',
  'Finance and Legal',
  'Business Finance',
  'Finance - Controllership',
  'Legal',
  'Taxation',
  'Global Operations',
  'Knowledge Management',
  'Risk Audit and Compliance',
  'Process Design and Automation',
  'Workforce Management',
  'Enterprise Program Management Office (EPMO)',
  'Operational Excellence',
  'People Practices & Systems',
  'HR Systems & Technology',
  'Talent Operations',
  'Talent Management and Engagement',
  'Talent Acquisition',
  'iAcademy',
  'Campus and Pool',
  'Organizational Development',
  'Sales Lifesciences',
  'Sales China',
  'Growth and Emerging Accounts',
  'Sales LifesSciences',
  'Key Accounts',
  'CultHealth',
  'Corporate Planning',
  'Global Delivery Center',
  'Emerging Biotech',
  'mySheets',
  'Activation Framework',
  'Amgen C 360',
  'All',
  'Indegene Products',
  'Management',
  'DT Consulting',
  'Commercial and Facilities',
  'Information Technology',
  'Editorial',
  'Marketing and Inside Sales'
];

/**
 * Find the best match from allowed values using fuzzy matching
 * Compatible with ES5 (no Array.find or String.includes)
 */
export function findBestMatch(value: string, allowedValues: string[]): string {
  if (!value || value.trim() === '') {
    return '';
  }

  const normalizedValue = value.trim().toLowerCase();
  
  // Exact match (case-insensitive)
  for (let i = 0; i < allowedValues.length; i++) {
    const allowed = allowedValues[i];
    if (allowed.toLowerCase() === normalizedValue) {
      return allowed;
    }
  }

  // Partial match (contains)
  for (let i = 0; i < allowedValues.length; i++) {
    const allowed = allowedValues[i];
    const allowedLower = allowed.toLowerCase();
    if (allowedLower.indexOf(normalizedValue) !== -1 || normalizedValue.indexOf(allowedLower) !== -1) {
      return allowed;
    }
  }

  // Fuzzy match - check if any words match
  const valueWords = normalizedValue.split(/\s+/);
  for (let i = 0; i < allowedValues.length; i++) {
    const allowed = allowedValues[i];
    const allowedWords = allowed.toLowerCase().split(/\s+/);
    
    for (let j = 0; j < valueWords.length; j++) {
      const word = valueWords[j];
      for (let k = 0; k < allowedWords.length; k++) {
        const allowedWord = allowedWords[k];
        if (allowedWord.indexOf(word) !== -1 || word.indexOf(allowedWord) !== -1) {
          return allowed;
        }
      }
    }
  }

  // No match found
  return '';
}

export const ALLOWED_DISEASE_AREAS = [
  'Noninfectious Uveitis',
  'Occular allergy',
  'Glucoma management',
  'Dry eye disease',
  'Diabetes',
  'Endometrial cancer',
  'Brain tumors',
  'Gastrointestinal cancer',
  'Coronavirus',
  'Esophageal Cancer',
  'Prostate Cancer',
  'Oncogenatic mutation',
  'Colorectal cancer',
  'Ovarian cancer',
  'B cell Acute lymphoblastic leukemia',
  'Mutiple Myeloma',
  'Metastatic colo-rectal Cancer',
  'Breast Cancer',
  'Gastric Cancer',
  'Hematology',
  'Solid Tumors',
  'Blood Cancers',
  'Lung Cancer'
];

export const ALLOWED_THERAPY_AREAS = [
  'Endocrinology',
  'Dermatology',
  'Gastroenterology',
  'Neurology',
  'Opthalmology',
  'Solid Tumors',
  'Hemet-Onco',
  'Nephrology',
  'Respiratory',
  'Rheumatology',
  'ENT',
  'Hepatology',
  'Gyneacology',
  'CVD',
  'Oncology'
];

export const ALLOWED_REGIONS = [
  'UK',
  'EUCAN',
  'Global',
  'APAC',
  'Australia',
  'Europe',
  'US'
];

export const ALLOWED_DOCUMENT_TYPES = [
  'Knowledge Fireside Chat',
  'Style Guide',
  'Reference',
  'Submissions',
  'Regulation',
  'Guidance',
  'Use Cases',
  'Glossary',
  'Workshop',
  'Email Template',
  'Reusable Assets',
  'News',
  'Narrative',
  'One-i Collaterals',
  'Catalo Connect',
  'Template',
  'Banner',
  'Abstract',
  'SOW',
  'Feedback',
  'Research Articles',
  'Web Designing',
  'Technology',
  'toastmasters',
  'Library Resource',
  'Knowledge Transfer',
  'Deck',
  'Success Story',
  'Prompt',
  'Contact',
  'Cheat Sheet',
  'Survey',
  'Covid Report',
  'Catalog',
  'SME Profile',
  'Handbook',
  'Governance Deck',
  'Playbook',
  'Training',
  'Updates',
  'External Link',
  'Community Page',
  'Q&A',
  'E-book',
  'About',
  'Story',
  'Publication',
  'SRL',
  'e poster',
  'Plain language summary',
  'Marketing Collateral',
  'Patient story video',
  'Win',
  'Logo',
  'Interactive Poster',
  'Static Newsletter',
  'Static Slide deck',
  'E Module',
  'Static Infographic',
  'Interactive Infographic',
  'Sample Profile',
  'Sample',
  'Toolkit',
  'Code of Conduct',
  'Proposals & Pitches',
  'Form',
  'Profile',
  'RACI Document',
  'Plan',
  'Insight',
  'Demo',
  'Battle Card',
  'Experience Master',
  'Email',
  'Leadership Connect',
  'Article',
  'Assessment',
  'Style Code',
  'Agreement',
  'Recording',
  'Overview Deck',
  'Org Chart',
  'Discussion',
  'Calendar',
  'Fact Sheet',
  'KS2',
  'Proactive',
  'Thought Leadership',
  'OKR',
  'Communication',
  'ESG',
  'iKnowledge Help',
  'Frequently Asked Questions (FAQs)',
  'Concept Note',
  'Others',
  'Product',
  'Ad Collateral',
  'Analyst Briefing Presentation',
  'Analyst Report',
  'Analyst RFIs or RFP',
  'Best Practice',
  'Blog',
  'Brand Resource',
  'Brochure',
  'Capability',
  'Case Study',
  'Certificate',
  'Checklist',
  'Council Asset',
  'Customer Presentations / Overview',
  'Customer RFI or RFP',
  'eBook',
  'eMagazine',
  'Email Campaign',
  'Event Asset',
  'Expertise Note',
  'Guidelines',
  'Image',
  'Infographic',
  'Internal Announcement',
  'Internal Report or Analysis',
  'Lessons Learned',
  'Manual',
  'Marketing Plan',
  'Newsletter',
  'Onboarding Package',
  'Physical Banner',
  'Pitch Deck',
  'Podcast',
  'Policy',
  'Press Release',
  'Process',
  'Proposal',
  'RFIs/RFP',
  'Sales Deck',
  'Social Media Post',
  'SOP',
  'Sponsored Content',
  'Standard',
  'Technical Document',
  'Templates / Reports',
  'Testimonial',
  'Third Party Report',
  'Tracker',
  'Training Document/ onboarding deck',
  'Video',
  'Webinar',
  'Webpage',
  'White Paper'
];

