
require("./QuestionSection.module.css");
const styles = {
  questionSection: 'questionSection_da1a1f17',
  tilesContainer: 'tilesContainer_da1a1f17',
  tile: 'tile_da1a1f17',
  promptText: 'promptText_da1a1f17',
  rightInput: 'rightInput_da1a1f17',
  questionInput: 'questionInput_da1a1f17',
  chatbotIcon: 'chatbotIcon_da1a1f17',
  chatWindow: 'chatWindow_da1a1f17',
  chatHeader: 'chatHeader_da1a1f17',
  messages: 'messages_da1a1f17',
  messageContainer: 'messageContainer_da1a1f17',
  messageContainerUser: 'messageContainerUser_da1a1f17',
  messageContainerBot: 'messageContainerBot_da1a1f17',
  messageAvatar: 'messageAvatar_da1a1f17',
  userMsg: 'userMsg_da1a1f17',
  botMsg: 'botMsg_da1a1f17',
  thinking: 'thinking_da1a1f17',
  pulse: 'pulse_da1a1f17',
  inputRow: 'inputRow_da1a1f17',
  chatInput: 'chatInput_da1a1f17',
  sendButton: 'sendButton_da1a1f17',
  closeButton: 'closeButton_da1a1f17',
  tileHeader: 'tileHeader_da1a1f17',
  fileTypeIcon: 'fileTypeIcon_da1a1f17',
  fileType: 'fileType_da1a1f17',
  tileTitle: 'tileTitle_da1a1f17',
  tileAbstract: 'tileAbstract_da1a1f17',
  tileActions: 'tileActions_da1a1f17',
  viewButton: 'viewButton_da1a1f17',
  downloadButton: 'downloadButton_da1a1f17',
  loading: 'loading_da1a1f17',
  noDocuments: 'noDocuments_da1a1f17',
  detailModal: 'detailModal_da1a1f17',
  chatLauncher: 'chatLauncher_da1a1f17'
};

export default styles;
