
require("./DocumentDetailPage.module.css");
const styles = {
  documentDetailPage: 'documentDetailPage_ea2b5c02',
  header: 'header_ea2b5c02',
  backButton: 'backButton_ea2b5c02',
  content: 'content_ea2b5c02',
  titleSection: 'titleSection_ea2b5c02',
  titleContent: 'titleContent_ea2b5c02',
  contentWrapper: 'contentWrapper_ea2b5c02',
  mainContent: 'mainContent_ea2b5c02',
  headerRow: 'headerRow_ea2b5c02',
  fileTypeIndicator: 'fileTypeIndicator_ea2b5c02',
  fileTypeIcon: 'fileTypeIcon_ea2b5c02',
  fileTypeText: 'fileTypeText_ea2b5c02',
  documentTitle: 'documentTitle_ea2b5c02',
  documentAbstract: 'documentAbstract_ea2b5c02',
  metadata: 'metadata_ea2b5c02',
  metadataItem: 'metadataItem_ea2b5c02',
  actionButtons: 'actionButtons_ea2b5c02',
  downloadButton: 'downloadButton_ea2b5c02',
  shareButton: 'shareButton_ea2b5c02',
  previewSection: 'previewSection_ea2b5c02',
  previewTitle: 'previewTitle_ea2b5c02',
  previewContainer: 'previewContainer_ea2b5c02',
  previewFrame: 'previewFrame_ea2b5c02',
  previewPlaceholder: 'previewPlaceholder_ea2b5c02',
  previewError: 'previewError_ea2b5c02',
  errorIcon: 'errorIcon_ea2b5c02',
  errorText: 'errorText_ea2b5c02',
  retryButton: 'retryButton_ea2b5c02',
  sidebar: 'sidebar_ea2b5c02',
  sidebarSection: 'sidebarSection_ea2b5c02',
  sidebarTitle: 'sidebarTitle_ea2b5c02',
  tagsContainer: 'tagsContainer_ea2b5c02',
  tag: 'tag_ea2b5c02',
  infoList: 'infoList_ea2b5c02',
  infoItem: 'infoItem_ea2b5c02',
  infoLabel: 'infoLabel_ea2b5c02',
  infoValue: 'infoValue_ea2b5c02',
  loading: 'loading_ea2b5c02',
  error: 'error_ea2b5c02'
};

export default styles;
